### ISSUE TITLE
Long/Queen Castling is incorrect

### ISSUE THREAD

**Issue by GitHubStefan13** [igormironchik/chess#1]
I don't know if you still want to maintain this Project.

Anyways i noticed that the castling is handled wrong.
You do not move the King from e1 to b1 for long Castling.

So you should change

> // Castling.
	if( figure->type() == Figure::KingFigure &&
		!figure->isFirstMoveDone() )
	{
		switch( figure->color() )
		{
			case Figure::White :
			{
				if( x == 1 )
				{
					if( board.figures()[ 7 ][ 0 ] &&
						!board.figures()[ 7 ][ 0 ]->isFirstMoveDone() )
							board.move( 0, 7, 2, 7 );
				}
				else if( x == 6 )
				{
					if( board.figures()[ 7 ][ 7 ] &&
						!board.figures()[ 7 ][ 7 ]->isFirstMoveDone() )
							board.move( 7, 7, 5, 7 );
				}
			}
				break;

			case Figure::Black :
			{
				if( x == 1 )
				{
					if( board.figures()[ 0 ][ 0 ] &&
						!board.figures()[ 0 ][ 0 ]->isFirstMoveDone() )
							board.move( 0, 0, 2, 0 );
				}
				else if( x == 6 )
				{
					if( board.figures()[ 0 ][ 7 ] &&
						!board.figures()[ 0 ][ 7 ]->isFirstMoveDone() )
							board.move( 7, 0, 5, 0 );
				}
			}
				break;

			default :
				break;
		}
	}
to

> // Castling.
	if( figure->type() == Figure::KingFigure &&
		!figure->isFirstMoveDone() )
	{
		switch( figure->color() )
		{
			case Figure::White :
			{
				if( x == 2 )
				{
					if( board.figures()[ 7 ][ 0 ] &&
						!board.figures()[ 7 ][ 0 ]->isFirstMoveDone() )
							board.move( 0, 7, 3, 7 );
				}
				else if( x == 6 )
				{
					if( board.figures()[ 7 ][ 7 ] &&
						!board.figures()[ 7 ][ 7 ]->isFirstMoveDone() )
							board.move( 7, 7, 5, 7 );
				}
			}
				break;

			case Figure::Black :
			{
				if( x == 2 )
				{
					if( board.figures()[ 0 ][ 0 ] &&
						!board.figures()[ 0 ][ 0 ]->isFirstMoveDone() )
							board.move( 0, 0, 3, 0 );
				}
				else if( x == 6 )
				{
					if( board.figures()[ 0 ][ 7 ] &&
						!board.figures()[ 0 ][ 7 ]->isFirstMoveDone() )
							board.move( 7, 0, 5, 0 );
				}
			}
				break;

			default :
				break;
		}
	}

AND

> // Castling highlight.
					if( figure->type() == Figure::KingFigure &&
						!figure->isFirstMoveDone() && !m_isChess )
					{
						if( !m_board.figures()[ y ][ x - 1 ] &&
							!m_board.figures()[ y ][ x - 2 ] &&
							!m_board.figures()[ y ][ x - 3 ] &&
							m_board.figures()[ y ][ x - 4 ] &&
							!m_board.figures()[ y ][ x - 4 ]->isFirstMoveDone() )
						{
							if( !isCheckAfterMove( x - 3, y, figure, tmpBoard ) )
							{
								m_possibleMoves.append( ( x - 3 ) * 10 + y );

								m_board.markBlue( x - 3, y );
							}
						}

TO

> // Castling highlight.
					if( figure->type() == Figure::KingFigure &&
						!figure->isFirstMoveDone() && !m_isChess )
					{
						if( !m_board.figures()[ y ][ x - 1 ] &&
							!m_board.figures()[ y ][ x - 2 ] &&
							m_board.figures()[ y ][ x - 4 ] &&
							!m_board.figures()[ y ][ x - 4 ]->isFirstMoveDone() )
						{
							if( !isCheckAfterMove( x - 2, y, figure, tmpBoard ) )
							{
								m_possibleMoves.append( ( x - 2 ) * 10 + y );

								m_board.markBlue( x - 2, y );
							}
						}

**Comment by igormironchik** [comment]
Thank you for the issue. I really didn't know rules in chess for long castling. Thanks again. Fixed.
